
#servicios
services:
  
  #crear bases de datos
    db:
      image: postgres:16.1
      container_name: db-companies
      restart: always
      volumes:
      # el volumen es para persistencia de datos aunque el container se caiga 
      # podemos ver que hay docker-entrypoint-initdb.d, en este fragmento se indica el init, lo cual hace que cada vez que se inicie el contenedor se van a leer esos archivos
      # docker compose up para que inicie el contenedor
        - ./sql:/docker-entrypoint-initdb.d
      environment:
      ## informacion de bases de datos
        POSTGRES_DB: 'companies'
        POSTGRES_USER: 'jorge'
        POSTGRES_PASSWORD: 'udemy'
      ports:
        - '5432:5432'